/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonTokenSol from "./carbonToken.sol";
export type { carbonTokenSol };
import type * as mangmentContractSol from "./mangmentContract.sol";
export type { mangmentContractSol };
export type { IERCToken } from "./IERCToken";
export type { NFTMarketplace } from "./NFTMarketplace";
export type { NftMinterContract } from "./NftMinterContract";
